In [1]:
import pandas as pd

# Reading  the data

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df

fever  bodyPain  age  runnyNose  diffBreath  infectionProbab
0    98.878479         1   97          1          -1                0
1    98.239358         0   91          1           0                1
2    99.500673         0   82          1           1                0
3    98.092572         0   17          0           1                0
4   100.474402         0   81          1          -1                1
..         ...       ...  ...        ...         ...              ...
94  101.855176         0   41          0          -1                0
95  100.451282         0   62          1           1                0
96  101.519960         1   62          0           0                0
97   99.324949         1   36          0          -1                0
98  101.948097         0   73          1          -1                1

[99 rows x 6 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   fever            99 non-null     float64
 1   bodyPain         99 non-null     int64  
 2   age              99 non-null     int64  
 3   runnyNose        99 non-null     int64  
 4   diffBreath       99 non-null     int64  
 5   infectionProbab  99 non-null     int64  
dtypes: float64(1), int64(5)
memory usage: 4.8 KB


In [5]:
df['fever'].value_counts()


98.500083     1
99.785611     1
100.047874    1
99.113065     1
101.847345    1
             ..
101.437352    1
98.115036     1
98.273576     1
101.641844    1
100.448849    1
Name: fever, Length: 99, dtype: int64

In [6]:
df.describe()

fever   bodyPain        age  runnyNose  diffBreath  \
count   99.000000  99.000000  99.000000  99.000000   99.000000   
mean   100.033025   0.424242  52.010101   0.464646   -0.020202   
std      1.266252   0.496743  28.791118   0.501287    0.832746   
min     98.001061   0.000000   1.000000   0.000000   -1.000000   
25%     98.947847   0.000000  26.500000   0.000000   -1.000000   
50%    100.087531   0.000000  53.000000   0.000000    0.000000   
75%    101.205942   1.000000  79.000000   1.000000    1.000000   
max    101.986525   1.000000  97.000000   1.000000    1.000000   

       infectionProbab  
count        99.000000  
mean          0.434343  
std           0.498193  
min           0.000000  
25%           0.000000  
50%           0.000000  
75%           1.000000  
max           1.000000

# Train-Test Splitting


In [7]:
import numpy as np

In [8]:
def data_split(data, ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data)*ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

In [9]:
train, test = data_split(df, 0.2)

In [10]:
train

fever  bodyPain  age  runnyNose  diffBreath  infectionProbab
73  100.416534         0   21          0           0                0
49  100.969532         0   84          0           1                0
70  101.961371         1   27          0          -1                0
68  100.991647         1    8          1           0                1
15  100.047874         1   16          1           0                1
..         ...       ...  ...        ...         ...              ...
60  101.112989         1   57          1           1                0
71   98.817020         0   63          1           0                1
14  101.712363         1   85          1          -1                1
92  101.437352         0   36          1           0                1
51   99.027417         1    2          0           0                0

[80 rows x 6 columns]

In [11]:
test

fever  bodyPain  age  runnyNose  diffBreath  infectionProbab
62   99.940665         0   36          0          -1                0
40   98.273576         0   90          1           1                0
95  100.451282         0   62          1           1                0
18   98.602025         1    1          1          -1                1
97   99.324949         1   36          0          -1                0
84  101.334097         1   50          0           0                1
64   98.841715         1    4          0           1                0
42   98.027240         1   44          1           1                0
10  100.818995         0   63          0          -1                1
0    98.878479         1   97          1          -1                0
31  101.512086         1   62          1          -1                1
76  101.205728         0   31          0           1                1
47   99.129989         1   73          1           1                0
26  100.432996         1   44          0          -1                0
44   98.307989         0   49          1          -1                0
4   100.474402         0   81          1          -1                1
22  101.411821         0   67          0          -1                0
12   99.337975         0   87          1           1                1
88  100.058664         0   80          1           0                1

In [12]:
X_train = train[{'fever','bodyPain','age','runnyNose','diffBreath'}].to_numpy()
X_train

array([[ 21.        ,   0.        , 100.4165343 ,   0.        ,
          0.        ],
       [ 84.        ,   0.        , 100.9695316 ,   1.        ,
          0.        ],
       [ 27.        ,   1.        , 101.9613707 ,  -1.        ,
          0.        ],
       [  8.        ,   1.        , 100.9916465 ,   0.        ,
          1.        ],
       [ 16.        ,   1.        , 100.0478737 ,   0.        ,
          1.        ],
       [ 72.        ,   0.        , 101.8117642 ,  -1.        ,
          0.        ],
       [ 22.        ,   1.        , 101.1843814 ,   0.        ,
          0.        ],
       [  9.        ,   0.        ,  98.10947224,   1.        ,
          1.        ],
       [  2.        ,   1.        ,  99.11306538,  -1.        ,
          1.        ],
       [ 68.        ,   0.        ,  98.00106063,   1.        ,
          1.        ],
       [ 88.        ,   0.        ,  99.24144395,   1.        ,
          0.        ],
       [ 41.        ,   0.        , 101.855

In [13]:
X_test = test[{'fever','bodyPain','age','runnyNose','diffBreath'}].to_numpy()
X_test

array([[ 36.        ,   0.        ,  99.94066519,  -1.        ,
          0.        ],
       [ 90.        ,   0.        ,  98.273576  ,   1.        ,
          1.        ],
       [ 62.        ,   0.        , 100.4512818 ,   1.        ,
          1.        ],
       [  1.        ,   1.        ,  98.60202452,  -1.        ,
          1.        ],
       [ 36.        ,   1.        ,  99.32494901,  -1.        ,
          0.        ],
       [ 50.        ,   1.        , 101.334097  ,   0.        ,
          0.        ],
       [  4.        ,   1.        ,  98.84171538,   1.        ,
          0.        ],
       [ 44.        ,   1.        ,  98.02724039,   1.        ,
          1.        ],
       [ 63.        ,   0.        , 100.8189948 ,  -1.        ,
          0.        ],
       [ 97.        ,   1.        ,  98.8784793 ,  -1.        ,
          1.        ],
       [ 62.        ,   1.        , 101.5120864 ,  -1.        ,
          1.        ],
       [ 31.        ,   0.        , 101.205

In [14]:
y_train = train[{'infectionProbab'}].to_numpy().reshape(80,)
y_test = test[{'infectionProbab'}].to_numpy().reshape(19,)

In [15]:
y_train


array([0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0], dtype=int64)

In [16]:
y_test

array([0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1],
      dtype=int64)

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
clf = LogisticRegression()
clf.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [23]:
infProb = clf.predict_proba([[102, 1, 22, 0, 0]]) # predict_proba function predicts the value(not having disease, having disease)
infProb

array([[0.64994391, 0.35005609]])

In [25]:
inputFeatures = [102, 1, 22, 0, 0]
infProb = clf.predict_proba([inputFeatures])[0][1] #fetching the having disease value
infProb

0.35005609093164425